telegram:
  botName: ***
  token: ***
filepath:
  main: .\src\main\resources\static
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dicepoker
    username: postgres
    password: postgres
  # Postgres
  postgres:
    maximum-pool-size: 10
    connection-test-query: select 1
    connection-timeout: 1000
    minimum-idle: 10
    idle-timeout: 600000
    max-lifetime: 180000
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
# Server Config
server:
  port: 8095
beta-tester:
  id: [***]
